spring:
  application:
    name: ecommerce-product # 给应用起个逻辑名称，服务注册、日志打印、配置区分时用

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ecommerce_user
    password: ecommerce_pwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

  messages:
    basename: messages
    encoding: UTF-8

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: product_producer_group

server:
  servlet:
    context-path: /ecommerce # 设置应用的上下文路径，所有接口前面会自动加这个前缀（Base URL）
  port: 8082

mybatis-plus:
  mapper-locations: classpath*:com/example/ecommerce/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台输出 SQL（开发调试用）
  global-config:
    db-config:
      id-type: auto   # ID生成策略（数据库自增）
      logic-delete-field: deleted      # 如果你使用逻辑删除
      logic-not-delete-value: 0
      logic-delete-value: 1
#提供者
dubbo:
  application:
    name: product-service
  protocol:
    name: dubbo
    port: 20889
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.example.ecommerce.dubbo.impl
